set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME WASI)
if(EXISTS "/opt/wasi-sdk/share/cmake/wasi-sdk-p1.cmake")
  set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/opt/wasi-sdk/share/cmake/wasi-sdk-p1.cmake")
elseif(EXISTS "$ENV{HOME}/vm/wasi-sdk/share/cmake/wasi-sdk-p1.cmake")
  set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "$ENV{HOME}/vm/wasi-sdk/share/cmake/wasi-sdk-p1.cmake")
else()
  set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/opt/wasi-sdk/share/cmake/wasi-sdk-p1.cmake")
endif()
